# Generated by Django 4.0.4 on 2022-05-31 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom', '0005_userbill_discounted_amount_userbill_discout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
